name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version:
          - 3.0
          - 3.1
          - 3.2
          - ruby-head
      allow_failures:
        - ruby-version: ruby-head

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y liblua5.4-dev

      - name: Run tests
        run: bundle exec rake test
